config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  get 'home/about'
  get 'home/index'
  root 'contacts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /contacts or /contacts.json
  def index
    @contacts = Contact.where(user_id: current_user)
  end

  # GET /contacts/1 or /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts or /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: "Contact was successfully created." }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1 or /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: "Contact was successfully updated." }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1 or /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "Contact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
  <%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-4">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div class="field col-4">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div class="field col-4">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="field col-4">
    <%= form.label :phone %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>

  <div class="field  col-4">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, class:"form-control" %>
  </div>

  <div class="field  col-4">    
    <%= form.text_field :user_id, id: :contact_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit class:"btn btn-success" %>
  </div>
<% end %>

<br>

app/views/contacts/edit.html.erb
<div class="container">
<br>
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact, class:"btn btn-secondary" %> |
<%= link_to 'Back', contacts_path, class:"btn btn-dark" %>
</div>

app/views/contacts/index.html.erb
<div class="container">

<br>
<h1>Contacts</h1>

<table class="table table-striped table-bordered">
  <thead class="table-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.first_name %></td>
        <td><%= contact.last_name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.twitter %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Delete', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path, class:"btn btn-secondary" %>

</div>

app/views/contacts/new.html.erb
<div class="container"><br>
    <h1>New Contact</h1>

    <%= render 'form', contact: @contact %> 

    <%= link_to 'Back', contacts_path, class:"btn btn-secondary" %>
</div>

app/views/contacts/show.html.erb
<div class="container">

<div class="bg-light p-5 rounded-lg m-3">
  <h1 class="display-4"><%= @contact.first_name %> <%= @contact.last_name %> </h1>
  <p class="lead">
  <p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @contact.twitter %>
</p>
  </p>
  <hr class="my-4">
  <p></p>
  <%= link_to 'Edit', edit_contact_path(@contact), class:"btn btn-primary" %>
  <%= link_to 'Back', contacts_path, class:"btn btn-secondary" %>
</div>

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'MyContactsApp', root_path, class:'navbar-brand' %>

<!-- <a class="navbar-brand" href="#">My ContactsApp</a> -->

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% if user_signed_in? %>

        <li class="nav-item">
        <%= link_to 'My Contacts', contacts_path, class: 'nav-link' %>          
        </li>

        <li class="nav-item">
        <%= link_to 'Add Contact', new_contact_path, class: 'nav-link' %>          
        </li>

        <li class="nav-item">
        <%= link_to 'About', home_about_path, class: 'nav-link' %>          
        </li>        

        <li class="nav-item">
        <%= link_to 'Profile', edit_user_registration_path, class: 'nav-link' %>          
        </li>

        <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>          
        </li>

        <% else %>

        <li class="nav-item">
        <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>          
        </li>

        <li class="nav-item">
        <%= link_to 'Sign In', user_session_path, class: 'nav-link' %>          
        </li>

        <% end %>
        
        
      </ul>
     <!--  
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      -->
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<br>
<div class='container'>
    <h1>MyContactsApp</h1>
    <p>Hello there, this is my Contacts CRUD App, a basic CRUD(an application where you can Create, Read, Update and Delete records) application with rails...</p>
    
    <p>Reach me out at <a target="blank" href="https://twitter.com/paulcabezadev">Twitter</a> or <a target="blank" href="https://www.linkedin.com/in/paul-cabeza-dev/">Linkedin</a>. </p>
</div>

app/views/home/index.html.erb
<br>
<div class='container'>
    <h1>MyContactsApp</h1>
    <p>Hello there, this is my Contacts CRUD App, a basic CRUD(an application where you can Create, Read, Update and Delete records) application with rails...</p>
    
    <p>Please note this is under construction...</p>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-primary alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
    <title>Contacts App</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header' %>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>